"""add task model

Revision ID: c4870b5aa7cc
Revises: a08c8c9a7b1e
Create Date: 2024-10-31 18:02:49.453774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4870b5aa7cc'
down_revision = 'a08c8c9a7b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
