"""add task model

Revision ID: dcc38dc81beb
Revises: c4870b5aa7cc
Create Date: 2024-11-01 16:37:44.301540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc38dc81beb'
down_revision = 'c4870b5aa7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
